version: '3.9'

volumes:
  mongodbdata:
    driver: local

services:

  # frontend:
  #   build:
  #     context: ./frontend/flight_tickets
  #     dockerfile: Dockerfile
  #   container_name: frontend
  #   ports:
  #     - "8080:80"

  gateway_service:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: gateway_service
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
    environment:
      GATEWAY_HOST: 0.0.0.0
      GATEWAY_PORT: 8081
      JWT_SECRET: my_secret
      MONGODB_URI: mongodb://mattia:pass@mongodb:27017/flight_tickets_db
    command: "npm start"

  users_service:
    build:
      context: ./backend/src/users
      dockerfile: Dockerfile
    container_name: users_service
    ports:
      - "3001:3001"
    depends_on:
      - mongodb
      - gateway_service
    environment:
      MONGODB_URI: mongodb://mattia:pass@mongodb:27017/flight_tickets_db
    command: "npm start"
  
  mongodb:
    image: mongo
    restart: always
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: flight_tickets_db
    volumes:
      - mongodbdata:/data/db
      - ./mongodb/init-mongo.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  # rabbitmq:
  #   image: rabbitmq:3-management
  #   restart: always
  #   container_name: rabbitmq
  #   ports:
  #     - "5672:5672"
  #     - "15672:15672"
  #   environment:
  #     RABBITMQ_DEFAULT_USER: user
  #     RABBITMQ_DEFAULT_PASS: password