version: '3.9'

volumes:
  mongodbdata:
    driver: local

services:

  frontend:
    build:
      context: ./frontend/flight_tickets
      dockerfile: Dockerfile
    container_name: frontend-container
    ports:
      - "8080:80"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-container
    depends_on:
      - mongodb
    environment:
      MONGODB_URI: mongodb://mattia:pass@mongodb:27017/flight_tickets_db
    command: "npm start"

  mongodb:
    image: mongo
    restart: always
    container_name: mongodb-container
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: flight_tickets_db
    volumes:
      - mongodbdata:/data/db
      - ./mongodb/init-mongo.js:/docker-entrypoint-initdb.d/mongo-init.js:ro