version: '3.9'

include:
  - ./backend/docker-compose.yaml

services:

  frontend:
    build:
      context: ./frontend/flight_tickets
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "8080:80"
    depends_on:
      - gateway_service